### ISSUE TITLE
Initial value

### ISSUE THREAD

**Issue by anisalibegic** [cetorres/dropdown_formfield#10]
Add an option to set an initial value of the form field.

**Comment by Stevelriemenbill** [comment]
Nice work!

> Add an option to set an initial value of the form field.

I am also interested in this feature!

**Comment by anisalibegic** [comment]
@Stevelriemenbill It looks like @cetorres already did that by merging https://github.com/cetorres/dropdown_formfield/pull/7 but he forgot to release a new version on pub.dev. Downloading source from pub.dev shows no initialValue.

@cetorres Please, can you release a new version of this package?

**Comment by cetorres** [comment]
@Stevelriemenbill @anisalibegic yes, I totally forgot to update it on pub.dev. Sorry. I just did and it should be available there already. Thanks for reminding me.
