### ISSUE TITLE
Support text overflow?? 

### ISSUE THREAD

**Issue by jgmartinss** [cetorres/dropdown_formfield#12]

**Comment by RafaelPlantard** [comment]
I guess it would be nice support it avoiding the following error:
![IMG_21FCAC057414-1](https://user-images.githubusercontent.com/5968478/80922601-a13b2a80-8d54-11ea-94f7-0cbf19ac777b.jpeg)

**Comment by RafaelPlantard** [comment]
Maybe duplicate of #8 issue.
